<?php include 'includes/constants.php'; ?>
<?php include 'includes/header.php'; ?>
<?php include 'includes/sidenav.php'; ?>
<?php include 'includes/banner.php'; ?>
<?php include 'includes/menubar.php'; ?>
<?php include 'includes/welcome.php'; ?>
<?php include 'includes/categories.php'; ?>
<?php include 'includes/logok.php'; ?>
<?php include 'includes/footer.php'; ?>
